-- Synthetic AtlasPay Db2-like schema

CREATE TABLE ATLAS_LIMIT_POLICY (
    PRODUCT_CODE        CHAR(4)      NOT NULL,
    JURISDICTION        CHAR(2)      NOT NULL,
    BASE_LIMIT          DECIMAL(9,2) NOT NULL,
    PRODUCT_MAX         DECIMAL(9,2) NOT NULL,
    JURIS_LIMIT         DECIMAL(9,2) NOT NULL,
    ACTIVE_FLAG         CHAR(1)      NOT NULL DEFAULT 'Y',
    EFFECTIVE_DATE      DATE         NOT NULL,
    LAST_REFRESH_TS     TIMESTAMP,
    PRIMARY KEY (PRODUCT_CODE, JURISDICTION, EFFECTIVE_DATE)
);

CREATE TABLE ATLAS_ACCOUNT_PRODUCT (
    ACCOUNT_ID          CHAR(12)     NOT NULL PRIMARY KEY,
    PRODUCT_CODE        CHAR(4)      NOT NULL,
    ACCOUNT_STATUS      CHAR(1)      NOT NULL,
    HOME_JURISDICTION   CHAR(2)      NOT NULL
);
